// lib/universities.ts
export const universitiesTR = [
  "Abant İzzet Baysal Üniversitesi",
  "Abdullah Gül Üniversitesi",
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Ahi Evran Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atatürk Üniversitesi",
  "Atılım Üniversitesi",
  "Avrasya Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Beykent Üniversitesi",
  "Bezmiâlem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bingöl Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Bursa Uludağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çukurova Üniversitesi",
  "Dicle Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Eskişehir Teknik Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Hatay Mustafa Kemal Üniversitesi",
  "Hitit Üniversitesi",
  "Iğdır Üniversitesi",
  "İnönü Üniversitesi",
  "İskenderun Teknik Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Kâtip Çelebi Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kayseri Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kocaeli Üniversitesi",
  "Konya Teknik Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "Mersin Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Pamukkale Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sakarya Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Selçuk Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Şırnak Üniversitesi",
  "Tokat Gaziosmanpaşa Üniversitesi",
  "Trakya Üniversitesi",
  "Ufuk Üniversitesi",
  "Uşak Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yalova Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
  // --- Vakıf Üniversiteleri ---
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Altınbaş Üniversitesi",
  "Antalya Bilim Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Başkent Üniversitesi",
  "Biruni Üniversitesi",
  "Bilkent Üniversitesi",
  "Doğuş Üniversitesi",
  "Fatih Sultan Mehmet Vakıf Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Haliç Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Işık Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İstinye Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Gedik Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Sağlık ve Teknoloji Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Tınaztepe Üniversitesi",
  "Kadir Has Üniversitesi",
  "Kapadokya Üniversitesi",
  "Koç Üniversitesi",
  "Konya Gıda ve Tarım Üniversitesi",
  "Lokman Hekim Üniversitesi",
  "Maltepe Üniversitesi",
  "MEF Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Özyeğin Üniversitesi",
  "Piri Reis Üniversitesi",
  "Sabancı Üniversitesi",
  "Sanko Üniversitesi",
  "TED Üniversitesi",
  "Tobb Ekonomi ve Teknoloji Üniversitesi",
  "Üsküdar Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yeni Yüzyıl Üniversitesi",
  "Yüksek İhtisas Üniversitesi",
]
